name: currency conversion build end deploy peckage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@main

      - name: setup node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: build with nodesj
        run: npm install
        run: npm run build
