name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

        env:
          PORT: 8000
          MONGODB_URL: mongodb+srv://testsinbiose007.8sftj72.mongodb.net
          MONGODB_USER: eduardo
          MONGODB_PASSWORD: root
          HASH_JWT: test
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start
